spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://10.23.12.161:3306/jdbc
    driver-class-name: com.mysql.jdbc.Driver
#    hikari:
#      schema:
#        - classpath: department.sql