#spring:
#  redis:
#    database: 0 # Redis 数据库索引（默认为 0）
#    host: 127.0.0.1 #Redis 服务器地址
#    port: 6379  # Redis 服务器连接端口
#    password: 123456 # Redis 服务器链接密码 （默认为空）
#    lettuce:
#      pool:
#        max-active: 8 # 连接池最大链接数（使用负值 表示没有限制）默认 8
#        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
#        max-idle: 8 # 链接池中的最大空闲连接 默认 8
#        min-idle: 0 # 连接池中国的最小空闲连接 默认 0


spring:
  redis:
    host: 10.23.12.161 #Redis 服务器地址
    port: 6388  # Redis 服务器连接端口